theme: jekyll-theme-midnight.


<html>
<body background="w3s.png">

<h1>I am Ricky</h1>
<p><a href="https://www.w3schools.com">Visit W3Schools.com!</a></p>
<p>The background attribute is not supported HTML5. Use CSS instead.</p>

</body>
</html>
