<<style type="text/css">

  .outer {
    /* The image used */
    background-image: https://i.pinimg.com/originals/5d/d8/ba/5dd8bac90f2d0aa5f9f8712c4ea2167e.jpg;
    /* Full height */
    height: 100%; 
    /* Center and scale the image nicely */
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  }  
  
  .bottomleft {
    position: absolute;
    bottom: -8px;
    left: 10%;
    width: 400px;
    font-weight: bold;
    color: #fff;
  }

    .bottomright {
    position: absolute;
    bottom: -10px;
    left: 50%;
    width: 400px;
    font-weight: bold;
    color: #fff;
  }

</style>

<div class="outer">
<div class="bottomleft">
<p><img src="https://i.pinimg.com/originals/02/4d/7c/024d7c2784b6648d426faec028274b25.png" alt="Ricky" height="90%" width="100%"></p>
</div>
  
<div class="bottomright">
<p><img src="https://i.pinimg.com/originals/a3/e3/af/a3e3af72a0c22fac0bf5c7273f845eff.png" alt="Thomas" height="90%" width="100%"></p>
</div>

theme: jekyll-theme-slate
